org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512m -XX:+UseSerialGC
kotlin.daemon.jvmopts=-Xmx512M -XX:+UseSerialGC
kotlin.compiler.execution.strategy=in-process
# Disable Kotlin incremental compilation to fix "Could not close incremental caches" error
kotlin.incremental=false
org.gradle.parallel=false
org.gradle.workers.max=1
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
